package com.example.medchannel.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "appointments")

public class Appointment {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String appointment_id;
    @DynamoDBAttribute
    private String patient_id;
    @DynamoDBAttribute
    private String doc_id;
    @DynamoDBAttribute
    private String appointment_date;
    @DynamoDBAttribute
    private String appointment_time;
    @DynamoDBAttribute
    private String remarks;
    @DynamoDBAttribute
    private String created_at;
    @DynamoDBAttribute
    private String updated_at;
}
