package com.example.medchannel.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "patients")
public class Patient {
    @DynamoDBHashKey(attributeName = "patient_id")
    @DynamoDBAutoGeneratedKey
    private String patient_id;
    @DynamoDBAttribute
    private String id;
    @DynamoDBAttribute
    private String address;
    @DynamoDBAttribute
    private String phone;
    @DynamoDBAttribute
    private String dob;
    @DynamoDBAttribute
    private String gender;
    @DynamoDBAttribute
    private String blood_type;
    @DynamoDBAttribute
    private String created_at;
    @DynamoDBAttribute
    private String updated_at;
}
